version: 2  # dbt的配置版本号

sources:  # 声明数据源
  - name: nyc_taxi  # 源的名称，在模型中引用时使用
    database: dataengine_learning  # 数据库名称
    schema: default     # schema名称
    tables:  # 声明具体的表
      - name: yellow_taxi_trips_in  # 黄色出租车数据表
      - name: green_taxi_trips_in   # 绿色出租车数据表
      - name: fhv_taxi_trips_in     # 网约车数据表
      - name: taxi_zone_lookup_in    # 地理位置信息表
models:
  - name: stg_yellow_tripdata
    description: "暂存黄色出租车数据"
    columns:
      - name: tripid
        description: "行程ID"
        tests:
          - unique  # 测试1：确保tripid是唯一的
          - not_null  # 测试2：确保tripid不为空
      - name: pickup_datetime
        description: "上车时间"
        tests:
          - not_null  # 测试3：确保pickup_datetime不为空

  - name: stg_green_tripdata
    description: "暂存绿色出租车数据"
    columns:
      - name: tripid
        description: "行程ID"
        tests:
          - unique  # 确保tripid是唯一的
          - not_null  # 确保tripid不为空
      - name: pickup_datetime
        description: "上车时间"
        tests:
          - not_null  # 确保pickup_datetime不为空
      - name: dropoff_datetime
        description: "下车时间"
        tests:
          - not_null  # 确保dropoff_datetime不为空
      - name: passenger_count
        description: "乘客数量"
        tests:
          - not_null  # 确保passenger_count不为空
      - name: trip_distance
        description: "行程距离"
        tests:
          - not_null  # 确保trip_distance不为空
      - name: fare_amount
        description: "车费金额"
        tests:
          - not_null  # 确保fare_amount不为空 
  - name: stg_taxi_zone_lookup
    columns:
      - name: locationid
        tests:
          - unique
          - not_null